### ISSUE TITLE
Magic storarge bug

### ISSUE THREAD

**Issue by Satyrrrr** [hocha113/CalamityOverhaul#20]
Every time i use the polymerizer it glitches the magic storage and im not allow to craft or take anything and if i do it completely deletes the item that i tried taking out when i reload the world.

**Comment by hocha113** [comment]
Okay, I understand the issue you’re encountering. I’ll try to reproduce the bug during multiplayer testing later and then work on adapting it. If all goes well, it will be fixed within 24 hours.

**Comment by hocha113** [comment]
The mod has been updated, and I've rewritten that part of the logic. It should be much more stable in multiplayer now.

**Comment by Satyrrrr** [comment]
yessuirrr it works thanks you
