### ISSUE TITLE
German Translate mistake

### ISSUE THREAD

**Issue by LeonMT1** [hocha113/CalamityOverhaul#21]
In the German translation mistake
![image](https://github.com/user-attachments/assets/e73fd95e-b522-4f15-ac78-5910d125baa5)
It should say: Zum Open-Source-Repository gehen :)
If it says “Mod-Open-Source-Repository” then that doesn’t sound good in German.

**Comment by hocha113** [comment]
Thank you for pointing out the issue with the translation. How about "Zum Quellcode-Repository des Mods gehen"?

**Comment by LeonMT1** [comment]
No Problem your sentence has a grammar mistake it would be called "Zum Quellcode-Repository der Mods gehen". But personally i wouldnt call it Quellcode-Repository instead "Open-Source-Repository".
